# Generated by Django 5.0.7 on 2024-08-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('data_emissao', models.DateTimeField()),
                ('destinatario', models.CharField(max_length=255)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chave_nota_fiscal', models.CharField(max_length=255)),
                ('xml', models.TextField(blank=True, null=True)),
                ('cnpj_emissor', models.CharField(max_length=18)),
                ('razao_social_emissor', models.CharField(max_length=255)),
            ],
        ),
    ]
