# Generated by Django 5.0.7 on 2024-08-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18)),
                ('numero', models.CharField(max_length=20)),
                ('cstat', models.CharField(blank=True, max_length=3, null=True)),
                ('xmotivo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico da Nota Fiscal',
                'verbose_name_plural': 'Históricos das Notas Fiscais',
            },
        ),
    ]
