# Generated by Django 5.0.7 on 2024-08-23 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0004_certificado_email_certificado_name'),
        ('nota_fiscal', '0002_historiconotafiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiconotafiscal',
            name='cnpj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='certificados.certificado'),
        ),
    ]
