# Generated by Django 5.0.7 on 2024-08-23 17:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0005_alter_certificado_validate'),
        ('nota_fiscal', '0003_alter_historiconotafiscal_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscal',
            name='cnpj_emissor',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='razao_social_emissor',
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='cnpj',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='emissao', to='certificados.certificado'),
            preserve_default=False,
        ),
    ]
