# Generated by Django 5.0.7 on 2024-08-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0004_remove_notafiscal_cnpj_emissor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiconotafiscal',
            name='xml_string',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
