# Generated by Django 5.0.7 on 2024-08-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0005_historiconotafiscal_xml_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiconotafiscal',
            name='resposta_string',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
