# Generated by Django 5.0.7 on 2024-08-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0006_historiconotafiscal_resposta_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='pdf_file_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='status',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='xml_file_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
