# Generated by Django 5.0.7 on 2024-08-31 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0006_certificado_uf'),
        ('nota_fiscal', '0007_notafiscal_pdf_file_name_notafiscal_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='chave_nota_fiscal',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='CartaCorrecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField()),
                ('n_seq_evento', models.IntegerField()),
                ('correcao', models.CharField(max_length=255)),
                ('chave_nota_Fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nota_fiscal.notafiscal', to_field='chave_nota_fiscal')),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissor', to='certificados.certificado')),
            ],
        ),
    ]
