# Generated by Django 5.0.7 on 2024-08-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0008_alter_notafiscal_chave_nota_fiscal_cartacorrecao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartacorrecao',
            name='motivo',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartacorrecao',
            name='retorno',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='cartacorrecao',
            name='status',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
    ]
