# Generated by Django 5.0.7 on 2024-08-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0009_cartacorrecao_motivo_cartacorrecao_retorno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartacorrecao',
            name='pdf_file_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartacorrecao',
            name='xml_file_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
