# Generated by Django 5.0.7 on 2024-09-02 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0011_alter_cartacorrecao_options_notacancelada'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacancelada',
            name='protocolo',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
