# Generated by Django 5.0.7 on 2024-09-04 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0013_notafiscal_numero_protocolo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartacorrecao',
            old_name='chave_nota_Fiscal',
            new_name='chave_nota_fiscal',
        ),
        migrations.RenameField(
            model_name='notacancelada',
            old_name='chave_nota_Fiscal',
            new_name='chave_nota_fiscal',
        ),
    ]
