# Generated by Django 5.0.7 on 2024-08-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('cnpj', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=255)),
                ('validate', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
