# Generated by Django 5.0.7 on 2024-08-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0002_certificado_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='file',
            field=models.FileField(upload_to='certificados/'),
        ),
    ]
