# Generated by Django 5.0.7 on 2024-08-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0004_certificado_email_certificado_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='validate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
