# Generated by Django 5.0.7 on 2024-08-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0005_alter_certificado_validate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='uf',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
    ]
