# Generated by Django 5.0.7 on 2024-09-04 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0006_certificado_uf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='email',
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificados.certificado')),
            ],
        ),
        migrations.CreateModel(
            name='EmailEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('chave', models.CharField(max_length=255)),
                ('emails', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificados.certificado')),
            ],
        ),
    ]
