# Generated by Django 5.0.7 on 2024-09-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0007_remove_certificado_email_email_emailenviado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailenviado',
            name='emails',
        ),
        migrations.AddField(
            model_name='emailenviado',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailenviado',
            name='result',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]

